### PR TITLE
Temporarily drop testing on Py2.7

### PR DESCRIPTION
**Pull request by cclauss**
https://devguide.python.org/versions/#unsupported-versions

### CODE REVIEW

**Comment by jayvdb** [comment]
Im happy to approve and merge if you can get the legacy_python workflow working.

**Comment by cclauss** [comment]
The problem is that GHA never seems to run the ubuntu-18.04 jobs.

**Comment by jayvdb** [comment]
Maybe leave it a day, to see if it runs the ubuntu-18.04 jobs; if not, we know that is no longer a reasonable approach.
I also tried https://github.com/jayvdb/nose3/tree/pyenv, but that didnt appear to work either.
Might need to manually install pyenv and tox to get the "dead" snakes working.

**Comment by jayvdb** [comment]
Possibly, just update .github/workflows/tox-gh.yml to what works in that workflow, and leave the other workflow as-is in this PR, and then we can at least get some of the envs working in CI again, and then work on the others in a separate PR

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
Thanks!

**Pull request merged**
